### ISSUE TITLE
airbnb fonts link does not work

### ISSUE THREAD

**Issue by ErinShen** [ricardo-bion/ggtech#11]
Hi Ricardo,

I was so excited to start plotting airbnb themed visualizations with ggtech.  However, the dropbox link for downloading airbnb's Circular font stopped working:

https://dl.dropboxusercontent.com/u/2364714/airbnb_ttf_fonts/Circular%20Air-Medium%203.46.45%20PM.ttf

Many thanks!
Erin

**Comment by ricardo-bion** [comment]
Fixed. They can be downloaded her:

```
download.file("https://github.com/ricardo-bion/ggtech/blob/master/Circular%20Air-Medium%203.46.45%20PM.ttf", "/Library/Fonts/Circular Air-Medium 3.46.45 PM.ttf", method="curl")

download.file("https://github.com/ricardo-bion/ggtech/blob/master/Circular%20Air-Bold%203.46.45%20PM.ttf", "/Library/Fonts/Circular Air-Bold 3.46.45 PM.ttf", method="curl")
```
