### ISSUE TITLE
Font scripting error

### ISSUE THREAD

**Issue by Eflores89** [ricardo-bion/ggtech#3]
I installed fonts as per the instructions, but this error keeps creeping up: 

`rsession[61577] <Error>: ATSFontGetPostScriptName failed: error -984.`

The graph is built correctly and it displays the theme accordingly, but after about 40 of the same error messages... 

Not sure if it has something to do with the fonts. 

Here is session info, maybe something will pop-up that i'm not seeing...

```
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.0.0 ggtech_0.1   

loaded via a namespace (and not attached):
 [1] labeling_0.3     colorspace_1.2-6 scales_0.3.0     plyr_1.8.3       tools_3.2.3     
 [6] gtable_0.1.2     Rcpp_0.12.3      grid_3.2.3       digest_0.6.9     munsell_0.4.3   
```

**Comment by ricardo-bion** [comment]
This error happens for the `theme_tech(theme="etsy")` only. 

For some reason, the font is stored by extrafontdb as ".", without the font name. You can confirm this with `extrafont::fonts()`.

That forced me to set the font family name for this font as ".", and ggplot2 freaks out about it.

https://github.com/ricardo-bion/ggtech/blob/master/R/theme_tech.R#L30

The error does not stop execution, but it is annoying. 

Not sure how to get around it right now.
